apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "fin-pfe-eks-sunflower"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/fin-platform-team/fin-catalog-claims"
    targetRevision: HEAD
    path: "claims/sunflower"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true